export default {
    LEAVE: 'leave',
    WORK: 'work',
    HOLIDAY: 'holiday',
    STACK_OVERFLOW: 'stackoverflow',
    JOBSDB: 'jobsdb',
    HKNEWS: 'hknews',
    HKGOLDEN: 'hkgolden',
    BUDDHA: 'buddha',
    BIBLE: 'bible',
    HKNOIT: 'hknoit',
    NOJ1314: 'noj1314',
    MARKSIX: 'marksix',
    ALL_ACTION: 'all',
    CGST_DETECT: 'cgst_detect',
    DAILY_COUNT: 'daily_count',
    IQ_QUESTION: 'iq',
    IQ_ANSWER: 'iqa',
    EXAM: 'exam',
};
