export default {
    TIME: 'time',
    LEAVE: 'leave',
    HOLIDAY_LEAVE: 'holiday_leave',
    WORK: 'work',
    NEXT_HOLIDAY: 'holiday',
    PUBLIC_HOLIDAYS: 'public_holidays',
    STACK_OVERFLOW: 'stackoverflow',
    JOBSDB: 'jobsdb',
    HKNEWS: 'hknews',
    HKGOLDEN: 'hkgolden',
    BUDDHA: 'buddha',
    BIBLE: 'bible',
    HKNOIT: 'hknoit',
    NOJ1314: 'noj1314',
    MARKSIX: 'marksix',
    ALL_ACTION: 'all',
    CGST_DETECT: 'cgst_detect',
    NSFW_DETECT: 'nsfw_detect',
    DAILY_COUNT: 'daily_count',
    SET_WORK_START_TIME: 'set_work_start',
    SET_WORK_END_TIME: 'set_work_end',
    IQ_QUESTION: 'iq',
    IQ_ANSWER: 'iqa',
    EXAM: 'exam',
    EVAL: 'eval',
};
